apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: "main"
    - name: app-name
      type: string
      default: "ci-cd-final-project"
    - name: build-image
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/ci-cd-final-project:latest"
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - cleanup
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: lint
      taskRef:
        name: flake8
        kind: ClusterTask
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: output

    - name: test
      taskRef:
        name: nose
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: output

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - test
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: $(params.build-image)

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
            oc expose deployment/$(params.app-name) --port=8080 || true
